# Generated by Django 3.1.6 on 2021-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
