# Generated by Django 3.1.6 on 2021-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_auto_20210402_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
