# Generated by Django 3.1.6 on 2021-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initialization',
            fields=[
                ('ipAddress', models.GenericIPAddressField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
